name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: docker pull skyparmar/custom_images:latest

      - name: Scan Docker image for vulnerabilities using Clair
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/clair-config quay.io/coreos/clair-git:latest -config=/clair-config/config.yaml -log-level=info -mode=http

      - name: Scan Docker image for vulnerabilities using Trivy
        run: |
          docker run --rm -v $(pwd):/workdir aquasec/trivy:latest image skyparmar/custom_images:latest

      - name: Check container running
        run: docker ps

        

