name: Pull and Push Third Pary Image 

on:
  workflow_dispatch:
    inputs:
      my_var:
        description: 'Value for MY_VAR'
        required: true
        default: 'Hello, World!'
      another_var:
        description: 'Value for ANOTHER_VAR'
        required: true
        default: '42'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo "MY_VAR=${{ inputs.my_var }}" >> $GITHUB_ENV
        echo "ANOTHER_VAR=${{ inputs.another_var }}" >> $GITHUB_ENV

    - name: Echo environment variables
      run: |
        echo "MY_VAR: $MY_VAR"
        echo "ANOTHER_VAR: $ANOTHER_VAR"

    - name: Print all environment variables
      run: env        

