name: Pull and Push Third Party Image

on:
  workflow_dispatch:
    inputs:
      my_var:
        description: 'Value for MY_VAR'
        required: true
        default: 'Hello, World!'
      another_var:
        description: 'Value for ANOTHER_VAR'
        required: true
        default: '42'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set and process environment variables
      run: |
        MY_VAR="${{ inputs.my_var }}"
        ANOTHER_VAR="${{ inputs.another_var }}"

        # Check if MY_VAR is lowercase and convert to uppercase
        if [[ "$MY_VAR" =~ ^[a-z]+$ ]]; then
          MY_VAR=$(echo "$MY_VAR" | tr '[:lower:]' '[:upper:]')
        fi

        # Check if ANOTHER_VAR is lowercase and convert to uppercase
        if [[ "$ANOTHER_VAR" =~ ^[a-z]+$ ]]; then
          ANOTHER_VAR=$(echo "$ANOTHER_VAR" | tr '[:lower:]' '[:upper:]')
        fi

        echo "MY_VAR=$MY_VAR" >> $GITHUB_ENV
        echo "ANOTHER_VAR=$ANOTHER_VAR" >> $GITHUB_ENV

    - name: Echo environment variables
      run: |
        echo "MY_VAR: $MY_VAR"
        echo "ANOTHER_VAR: $ANOTHER_VAR"

    - name: Print all environment variables
      run: env
